---
title: "Prepare tensor"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Prepare tensor}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(magrittr)
library(dplyr)
library(torch)
library(torchts)
```

The basic notion what every deep learning novice should know is **tensor**. 
Tensor is an abstract mathematical structure representing an organized set of numbers. 
The simplest example of tensor is vector, which can be interpreted as a 1-dimensional tensor.
The next one is the order is **matrix**, a 2-dimensional tensor.

```{r mts}
# https://faculty.chicagobooth.edu/ruey-s-tsay/research/multivariate-time-series-analysis-with-r-and-financial-applications
# Mcomp
# https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781783552078/1/ch01lvl1sec08/multivariate-time-series-analysis
# as_tensor(EuStockMarkets, value, index)

# Optimizing MAPE
# 

```


[Best way to optimize MAPE](https://stats.stackexchange.com/questions/213897/best-way-to-optimize-mape)
[Mean Absolute Percentage Error for regression models](https://arxiv.org/abs/1605.02541)
[N-BEATS neural network for mid-term electricity load forecasting](https://gdudek.el.pcz.pl/files/N-Beats_MTLF.pdf)
https://pytorch-forecasting.readthedocs.io
